# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HyperSnapDemoApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'HyperSnapSDK', :path => '../'

#pod 'HyperSnapSDK', '2.4.6'


end
