# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HyperSnapDemoApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
 # use_frameworks!

pod 'HyperSnapSDK', :path => '../'

#pod 'HyperSnapSDK'#, '2.4.6'

#pod 'HyperSnapSDK', :git => 'https://github.com/hyperverge/capture-ios-sdk.git', :commit => 'b61e360638acb291a7991f49623a1ce3e6953606'



end
