# This is a basic workflow to help you get started with Actions

name: Release-HyperSnapSDK

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  # pull_request:
    # branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands to create tag (x.y.z) and push it to origin
      - name: Create a tag for version x.y.z
        run: |
          git tag "x.y.z"
          git push origin --tags

      # Runs a set of commands to push HyperSnapSDK (x.y.z) to cocoapods
      # - name: Push HyperSnapSDK (x.y.z) to cocoapods
      #  run: |
      #   pod spec lint HyperSnapSDK.podspec --allow-warnings --verbose
      #   pod trunk push HyperSnapSDK.podspec --allow-warnings
      
      # Runs a command to let you know that HyperSnapSDK (x.y.z) has been released
      - name: Log HyperSnapSDK (x.y.z) release
        run: |
          echo HyperSnapSDK (x.y.z) has been pushed to cocoapods
